apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-query-understand
  namespace: softwaredoug-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-query-understand
  template:
    metadata:
      labels:
        app: llm-query-understand
    spec:
      containers:
      - name: fastapi
        image: gcr.io/YOUR_PROJECT_ID/fastapi-gke:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "12Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "2"
        volumeMounts:
          - name: model-cache
            mountPath: /root/.cache/huggingface
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache-pvc
