apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-pvc
  namespace: softwaredoug-training
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
