apiVersion: v1
kind: Service
metadata:
  name: llm-query-understand
  namespace: softwaredoug-training
spec:
  type: LoadBalancer
  selector:
    app: llm-query-understand
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
